# Site settings
title: Anastasia Aladysheva
email: aladysheva@sipri.org
description: > # this means to ignore newlines until "baseurl:"
 
[Research](https://aladysheva.github.io/research)
[CV](https://aladysheva.github.io/cv)
[Blog](https://aladysheva.github.io/blog)
[Contact](https://aladysheva.github.io/contact) 
 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aladysheva.com" # the base hostname & protocol for your site
github_username:  aladysheva
permalink: /:title/ #/blog/:year/:month/:title.html
gems:
  - jekyll-sitemap
  - jekyll-feed
# Build settings
markdown: kramdown


theme: jekyll-theme-minimal
