# Site settings
#title: Anastasia Aladysheva
title:
email: aladysheva@sipri.org
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username: 
permalink:  #/blog/:year/:month/:title.html
gems:
  - jekyll-sitemap
  - jekyll-feed
# Build settings
markdown: kramdown
theme: minima
